export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SIGNUP = 'SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const NEWEVENT = 'NEWEVENT';
export const NEWEVENT_SUCCESS = 'NEWEVENT_SUCCESS';
export const NEWEVENT_FAILURE = 'NEWEVENT_FAILURE';